### ISSUE TITLE
when runing cartpole_ppo_rnd_main.py, some bug is coming.

### ISSUE THREAD

**Issue by jgp-github** [opendilab/DI-engine#294]
hi, when runing cartpole_ppo_rnd_main.py, some bug is coming. I  want to know the reason and the corresponding solution. the bug is below. looking forward your answer.

Traceback (most recent call last):
  File "/home/jgp/.conda/envs/jgpenv/lib/python3.8/site-packages/dizoo/classic_control/cartpole/entry/cartpole_ppo_rnd_main.py", line 70, in <module>
    main(cartpole_ppo_rnd_config)
  File "/home/jgp/.conda/envs/jgpenv/lib/python3.8/site-packages/dizoo/classic_control/cartpole/entry/cartpole_ppo_rnd_main.py", line 60, in main
    reward_model.train()
  File "/home/jgp/.conda/envs/jgpenv/lib/python3.8/site-packages/ding/reward_model/rnd_reward_model.py", line 97, in train
    self._train()
  File "/home/jgp/.conda/envs/jgpenv/lib/python3.8/site-packages/ding/reward_model/rnd_reward_model.py", line 81, in _train
    if self.cfg.obs_norm:
AttributeError: 'EasyDict' object has no attribute 'obs_norm'

**Comment by PaParaZz1** [comment]
You can try [this config file](https://github.com/opendilab/DI-engine/blob/main/dizoo/classic_control/cartpole/config/cartpole_rnd_onppo_config.py) now, just enter `python3 -u cartpole_rnd_onppo_config.py`. (commit id: 5df6e768ba13f80b9aba1fe6b860651764fe8b29)

**Comment by jgp-github** [comment]
OK, thanks
