### ISSUE TITLE
How to use DingEnvWrapper in config files?

### ISSUE THREAD

**Issue by cpwan** [opendilab/DI-engine#437]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [x] documentation request
    + [x] new feature request
- [x] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [x] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
  # v0.4.0 1.10.0+cu102 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:18)
  # [GCC 10.3.0] linux
  ```
------------

I have a follow-up question for #264. Now, I am using the [DingEnvWrapper](https://di-engine-docs.readthedocs.io/en/latest/04_best_practice/ding_env.html#dingenvwrapper) to convert my `gym.Env` to `BaseEnv`.

How do I write the config files like [those in dizoo](https://di-engine-docs.readthedocs.io/en/latest/11_dizoo/index.html#how-to-use-di-zoo) so that it does the wrapping automatically and I can run the training like the examples in dizoo?

Now, my env is defined as a `MyProblemEnv(gym.Env)` class in  `dizoo/myproblem/envs/myproblem_env.py`.
```shell
DI-engine/dizoo/myproblem
├── __init__.py
├── config
│   ├── __init__.py
│   └── myproblem_a2c_config.py
└── envs
    ├── __init__.py
    └── myproblem_env.py
```

## First Attempt
I modified the [line 41](https://github.com/opendilab/DI-engine/blob/63861b9357bb14f399f1df64f5d0b04a79d84dc9/dizoo/classic_control/cartpole/config/cartpole_a2c_config.py#L41) of the `cartpole_a2c_config.py`.
```python
cartpole_a2c_create_config = dict(
    env=dict(
        type='myproblem',  # changed
        import_names=['dizoo.myproblem.envs.myproblem_env'],  # changed
    ),
    env_manager=dict(type='base'),
    policy=dict(type='a2c'),
)
```
When I run `python dizoo/myproblem/config/myproblem_a2c_config.py` under the `DI-engine` directory, it gave me `ModuleNotFoundError: No module named 'dizoo.myproblem'`

<details>
  <summary>Show Traceback</summary>
 
```shell
Traceback (most recent call last):
  File "dizoo/myproblem/config/myproblem_a2c_config.py", line 75, in <module>
    serial_pipeline_onpolicy((main_config, create_config), seed=0)
  File "/opt/conda/envs/di-engine/lib/python3.8/site-packages/ding/entry/serial_entry_onpolicy.py", line 47, in serial_pipeline_onpolicy
    cfg = compile_config(cfg, seed=seed, env=env_fn, auto=True, create_cfg=create_cfg, save_cfg=True)
  File "/opt/conda/envs/di-engine/lib/python3.8/site-packages/ding/config/config.py", line 358, in compile_config
    env = get_env_cls(create_cfg.env)
  File "/opt/conda/envs/di-engine/lib/python3.8/site-packages/ding/envs/env/base_env.py", line 167, in get_env_cls
    import_module(cfg.get('import_names', []))
  File "/opt/conda/envs/di-engine/lib/python3.8/site-packages/ding/utils/import_helper.py", line 107, in import_module
    importlib.import_module(name)
  File "/opt/conda/envs/di-engine/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'dizoo.myproblem'
```

</details>

## Second Attempt

I register my gym.Env and the wrapper in the beginning of `__main__`. 
```python
def register_env():
    import sys, os
    sys.path.insert(1, os.path.join(sys.path[0], '../../../'))
    
    import gym
    from easydict import EasyDict
    from ding.envs.env import DingEnvWrapper
    
    env_id = "myproblem-v0"
    gym.envs.register(
        id=env_id,
        entry_point="dizoo.myproblem.envs.myproblem_env:MyProblemEnv",
    )
    env_cfg = EasyDict(env_id=env_id)
    ding_env = DingEnvWrapper(cfg=env_cfg)
    ding_env.reset()
```

With this `register_env` function called, I can import `dizoo.myproblem`. But this time, it gave me `KeyError: 'myproblem'` when I run the `myproblem_a2c_config.py`.

<details>
  <summary>Show Traceback</summary>
 
```shell
Traceback (most recent call last):
  File "dizoo/myproblem/config/myproblem_a2c_config.py", line 75, in <module>
    serial_pipeline_onpolicy((main_config, create_config), seed=0)
  File "/home/path/to/DI-engine/dizoo/myproblem/config/../../../ding/entry/serial_entry_onpolicy.py", line 47, in serial_pipeline_onpolicy
    cfg = compile_config(cfg, seed=seed, env=env_fn, auto=True, create_cfg=create_cfg, save_cfg=True)
  File "/home/path/to/DI-engine/dizoo/myproblem/config/../../../ding/config/config.py", line 358, in compile_config
    env = get_env_cls(create_cfg.env)
  File "/home/path/to/DI-engine/dizoo/myproblem/config/../../../ding/envs/env/base_env.py", line 168, in get_env_cls
    return ENV_REGISTRY.get(cfg.type)
  File "/home/path/to/DI-engine/dizoo/myproblem/config/../../../ding/utils/registry.py", line 77, in get
    return self[module_name]
KeyError: 'myproblem'
```

</details>

## Third attempt (on-going)
It seems that I need to add the `@ENV_REGISTRY.register('myproblem') ` decorator to my `MyProblemEnv(gym.Env)`, inheriting it with `BaseEnv`, and add the missing abstract functions. However, I want to avoid changing the original class and use the `DingEnvWrapper` instead. How do I do that?

**Comment by PaParaZz1** [comment]
You can try the following solution (modified from your second attempt):
```python
def register_env():
    import sys, os
    sys.path.insert(1, os.path.join(sys.path[0], '../../../'))
    
    import gym
    from easydict import EasyDict
    from ding.envs.env import DingEnvWrapper
    
    env_id = "myproblem-v0"
    # this env_id is registered in gym rather than ding
    gym.envs.register(
        id=env_id,
        entry_point="dizoo.myproblem.envs.myproblem_env:MyProblemEnv",
    )
    return env_id

def main():
    env_id = register_env()
    def env_fn(env_cfg):
        return DingEnvWrapper(gym.make(env_id), cfg=env_cfg)
    # env_fn, collector_env_cfg, evaluator_env_cfg
    env_setting = [env_fn, [{} for _ in range(collector_env_num)], [{} for _ in range(evaluator_env_num)]]
    serial_pipeline_onpolicy((main_config, create_config), seed=0, env_setting=env_setting)
```

**Comment by cpwan** [comment]
Thanks. I am able to get it running.

**Comment by luxiaolei** [comment]
May I ask what if `MyProblemEnv` is a subclass of `ding.envs.BaseEnv`, how can this pipeline be done? @PaParaZz1 thanks alot in advance.
