### ISSUE TITLE
TypeError: Cannot create a consistent method resolution

### ISSUE THREAD

**Issue by jaried** [opendilab/DI-engine#459]
-  I have marked all applicable categories:
    +  exception-raising bug
-  I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
-  I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
-  I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
v0.4.1 1.12.1+cu116 3.8.0 (default, Nov  6 2019, 16:00:02) [MSC v.1916 64 bit (AMD64)] win32
  ```
我在运行dizoo/multiagent_mujoco/config/ant_masac_config.py时，报错，错误如下，请问如何解决？
```python
python.exe DI-engine-main/dizoo/multiagent_mujoco/config/ant_masac_config.py
Traceback (most recent call last):
  File "DI-engine-main/dizoo/multiagent_mujoco/config/ant_masac_config.py", line 73, in <module>
    from ding.entry.serial_entry import serial_pipeline
  File ".\DI-engine-main\ding\entry\__init__.py", line 1, in <module>
    from .cli import cli
  File ".\DI-engine-main\ding\entry\cli.py", line 9, in <module>
    from ding.config import read_config
  File ".\DI-engine-main\ding\config\__init__.py", line 1, in <module>
    from .config import Config, read_config, save_config, compile_config, compile_config_parallel, read_config_directly, \
  File ".\DI-engine-main\ding\config\config.py", line 14, in <module>
    from ding.envs import get_env_cls, get_env_manager_cls, BaseEnvManager
  File ".\DI-engine-main\ding\envs\__init__.py", line 1, in <module>
    from .env import *
  File ".\DI-engine-main\ding\envs\env\__init__.py", line 1, in <module>
    from .base_env import BaseEnv, get_vec_env_setting, BaseEnvTimestep, get_env_cls, create_model_env
  File ".\DI-engine-main\ding\envs\env\base_env.py", line 13, in <module>
    class FinalMeta(type(gym.Env), type(ABC)):
TypeError: Cannot create a consistent method resolution
order (MRO) for bases type, ABCMeta

Process finished with exit code 1

```

**Comment by PaParaZz1** [comment]
这是 gym 最近版本更新处理兼容性时带来的一个 bug，暂时性的解决办法是安装`gym==0.25.1`，根本性的解决办法我们会在下周发布的 v0.4.2 版本中给出。

**Comment by jaried** [comment]
谢谢您的回答。安装`gym==0.25.1` 后，没出现该问题。后面还有mujoco的问题，我自己再检查检查。有需要我再打开issue。

**Comment by jaried** [comment]
安装`gym==0.25.1`后，执行到后面依然报错：

```

Traceback (most recent call last):
  File ".\DI-engine-main\ding\envs\env_manager\base_env_manager.py", line 107, in __init__
    self._observation_space = self._env_ref.observation_space
  File ".\DI-engine-main\dizoo\multiagent_mujoco\envs\multi_mujoco_env.py", line 104, in observation_space
    return self._observation_space
AttributeError: 'MujocoEnv' object has no attribute '_observation_space'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File ".\DI-engine-main\dizoo\multiagent_mujoco\envs\mujoco_multi.py", line 92, in __init__
    self.wrapped_env = NormalizedActions(gym.make(self.scenario))
  File "D:\Anaconda3\envs\python38_env\lib\site-packages\gym\envs\registration.py", line 662, in make
    env = env_creator(**_kwargs)
  File "D:\Anaconda3\envs\python38_env\lib\site-packages\gym\envs\mujoco\ant.py", line 24, in __init__
    MuJocoPyEnv.__init__(
  File "D:\Anaconda3\envs\python38_env\lib\site-packages\gym\envs\mujoco\mujoco_env.py", line 233, in __init__
    raise error.DependencyNotInstalled(
gym.error.DependencyNotInstalled: No module named 'mujoco_py'. (HINT: you need to install mujoco_py, and also perform the setup instructions here: https://github.com/openai/mujoco-py/.)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File ".\DI-engine-main\ding\utils\registry.py", line 96, in build
    raise e
  File ".\DI-engine-main\ding\utils\registry.py", line 82, in build
    return build_fn(*obj_args, **obj_kwargs)
  File ".\DI-engine-main\ding\envs\env_manager\subprocess_env_manager.py", line 215, in __init__
    super().__init__(env_fn, cfg)
  File ".\DI-engine-main\ding\envs\env_manager\base_env_manager.py", line 116, in __init__
    self._env_ref.reset()
  File ".\DI-engine-main\dizoo\multiagent_mujoco\envs\multi_mujoco_env.py", line 27, in reset
    self._env = MujocoMulti(env_args=self._cfg)
  File ".\DI-engine-main\dizoo\multiagent_mujoco\envs\mujoco_multi.py", line 101, in __init__
    raise NotImplementedError('Custom env not implemented!')
NotImplementedError: Custom env not implemented!
python-BaseException

```

**Comment by PaParaZz1** [comment]
多个报错看第一个出现的报错。这个问题是你的运行环境没有安装`mujoco_py`这个库吧，你可以自行安装，或者用我们提供好的docker: opendilab/ding:nightly-mujoco

**Comment by jaried** [comment]
谢谢！
