### ISSUE TITLE
AttributeError: 'MujocoEnv' object has no attribute '_observation_space'

### ISSUE THREAD

**Issue by jaried** [opendilab/DI-engine#473]
-  I have marked all applicable categories:
    +  exception-raising bug
-  I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
-  I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
-  I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
v0.4.1 1.12.1+cu102 3.9.13 (main, Aug 25 2022, 23:26:10) 
[GCC 11.2.0] linux
  ```
运行[ant_masc_config.py](https://github.com/opendilab/DI-engine/blob/main/dizoo/multiagent_mujoco/config/ant_masac_config.py)时，报错，错误如下，请问，如何解决：

```python
Traceback (most recent call last):
  File "/home/tony/documents/DI-engine-main/ding/envs/env_manager/base_env_manager.py", line 111, in __init__
    self._observation_space = self._env_ref.observation_space
  File "/home/tony/documents/DI-engine-main/dizoo/multiagent_mujoco/envs/multi_mujoco_env.py", line 98, in observation_space
    return self._observation_space
AttributeError: 'MujocoEnv' object has no attribute '_observation_space'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tony/documents/DI-engine-main/ding/utils/registry.py", line 96, in build
    raise e
  File "/home/tony/documents/DI-engine-main/ding/utils/registry.py", line 82, in build
    return build_fn(*obj_args, **obj_kwargs)
  File "/home/tony/documents/DI-engine-main/ding/envs/env_manager/subprocess_env_manager.py", line 216, in __init__
    super().__init__(env_fn, cfg)
  File "/home/tony/documents/DI-engine-main/ding/envs/env_manager/base_env_manager.py", line 120, in __init__
    self._env_ref.reset()
  File "/home/tony/documents/DI-engine-main/dizoo/multiagent_mujoco/envs/multi_mujoco_env.py", line 29, in reset
    obs = self._env.reset()
  File "/home/tony/documents/DI-engine-main/dizoo/multiagent_mujoco/envs/mujoco_multi.py", line 222, in reset
    obs = {'agent_state': self.get_obs(), 'global_state': self.get_state()}
  File "/home/tony/documents/DI-engine-main/dizoo/multiagent_mujoco/envs/mujoco_multi.py", line 189, in get_state
    state_n.append(self.env._get_obs())
  File "/home/tony/anaconda3/envs/python39/lib/python3.9/site-packages/gym/core.py", line 324, in __getattr__
    raise AttributeError(f"accessing private attribute '{name}' is prohibited")
AttributeError: accessing private attribute '_get_obs' is prohibited
```

**Comment by PaParaZz1** [comment]
这个问题是因为 gym>=0.25.0 之后新增了对私有属性的限制 https://github.com/openai/gym/blob/master/gym/core.py#L239
而原始的 multi-agent mujoco 环境确实是通过使用 `_get_obs` 方法来获取必要信息的，所以就产生了冲突，因此不兼容而报错

**Comment by jaried** [comment]
那我先降级gym=0.24.1试试

**Comment by PaParaZz1** [comment]
- 在这个commit中先暴力修复了一下 https://github.com/opendilab/DI-engine/commit/b964cf2eb624f8d1568f4616f0f1bfdf23dac5cd ，其实本质就是要用这个方法 https://github.com/openai/gym/blob/master/gym/envs/mujoco/ant.py#L61
- 或者你也降级到 gym==0.22.0 来使用

**Comment by jaried** [comment]
那就先降级到gym==0.22.0吧

**Comment by jaried** [comment]
还不能降级到0.22.0
```python
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
di-engine 0.4.1 requires gym>=0.25.0, but you have gym 0.22.0 which is incompatible.

```
