### ISSUE TITLE
Env 0 reset has exceeded max retries(5)   

### ISSUE THREAD

**Issue by jaried** [opendilab/DI-engine#494]
- [ ] I have marked all applicable categories:
    + [x] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [ ] documentation request
    + [ ] new feature request
- [ ] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [ ] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable:
```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
v0.4.3 1.12.1+cu116 3.9.13 (main, Aug 25 2022, 23:26:10) 
[GCC 11.2.0] linux
```

我的代码如下：
https://github.com/jaried/study_di/blob/main/option_masac_config.py
我尝试用masac写代码，出现如下错误，请问，我该如何解决？

```python
[09-23 12:02:55] ERROR    Env 0 reset has exceeded max retries(5)                                                                                               func.py:27
Traceback (most recent call last):
  File "/home/tony/documents/DI-engine-main/ding/utils/system_helper.py", line 57, in run
    self.ret = self._target(*self._args, **self._kwargs)
  File "/home/tony/documents/DI-engine-main/ding/envs/env_manager/subprocess_env_manager.py", line 461, in _reset
    raise runtime_error
  File "/home/tony/documents/DI-engine-main/ding/envs/env_manager/subprocess_env_manager.py", line 439, in _reset
    reset_fn()
  File "/home/tony/documents/DI-engine-main/ding/envs/env_manager/subprocess_env_manager.py", line 425, in reset_fn
    raise ConnectionError("env reset connection timeout")  # Leave it to try again
RuntimeError: Env 0 reset has exceeded max retries(5), and the latest exception is: ConnectionError('env reset connection timeout')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tony/documents/DI-engine-main/ding/utils/registry.py", line 96, in build
    raise e
  File "/home/tony/documents/DI-engine-main/ding/utils/registry.py", line 82, in build
    return build_fn(*obj_args, **obj_kwargs)
  File "/home/tony/documents/DI-engine-main/ding/worker/collector/sample_serial_collector.py", line 65, in __init__
    self.reset(policy, env)
  File "/home/tony/documents/DI-engine-main/ding/worker/collector/sample_serial_collector.py", line 130, in reset
    self.reset_env(_env)
  File "/home/tony/documents/DI-engine-main/ding/worker/collector/sample_serial_collector.py", line 80, in reset_env
    self._env.launch()
  File "/home/tony/documents/DI-engine-main/ding/envs/env_manager/subprocess_env_manager.py", line 352, in launch
    self.reset(reset_param)
  File "/home/tony/documents/DI-engine-main/ding/envs/env_manager/subprocess_env_manager.py", line 409, in reset
    t.join()
  File "/home/tony/documents/DI-engine-main/ding/utils/system_helper.py", line 64, in join
    raise RuntimeError('Exception in thread({})'.format(id(self))) from self.exc
RuntimeError: Exception in thread(139979215706288)

Process finished with exit code 1
```

**Comment by PaParaZz1** [comment]
你的环境是什么，这个报错显示的是 reset 超时，默认应该设置的是60s

**Comment by jaried** [comment]
环境已经贴在上面：
v0.4.3 1.12.1+cu116 3.9.13 (main, Aug 25 2022, 23:26:10) 
[GCC 11.2.0] linux
代码在：
https://github.com/jaried/study_di/blob/main/option_masac_config.py

**Comment by PaParaZz1** [comment]
这个是指你的RL环境，不是运行环境。你换成BaseEnvManager试试呢
