### ISSUE TITLE
minigrid_r2d2_config.py  error

### ISSUE THREAD

**Issue by mao-xu** [opendilab/DI-engine#496]
Hi， I install the id-engine and minigrid as recommended. 
When I run  python dizoo/minigrid/config/minigrid_r2d2_config.py ,  I get the following error:

  File "/home/lab/anaconda3/envs/id2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lab/anaconda3/envs/id2/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (5x2835 and 2739x128)
Exception ignored in: <function SampleSerialCollector.__del__ at 0x7fb1cecedf80>
Traceback (most recent call last):
  File "/home/lab/anaconda3/envs/id2/lib/python3.7/site-packages/ding/worker/collector/sample_serial_collector.py", line 195, in __del__
    self.close()
  File "/home/lab/anaconda3/envs/id2/lib/python3.7/site-packages/ding/worker/collector/sample_serial_collector.py", line 185, in close
    self._env.close()
  File "/home/lab/anaconda3/envs/id2/lib/python3.7/site-packages/ding/envs/env_manager/subprocess_env_manager.py", line 765, in close
    p.send(['close', None, None])
  File "/home/lab/anaconda3/envs/id2/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/lab/anaconda3/envs/id2/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/home/lab/anaconda3/envs/id2/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <function InteractionSerialEvaluator.__del__ at 0x7fb1cec950e0>
Traceback (most recent call last):
  File "/home/lab/anaconda3/envs/id2/lib/python3.7/site-packages/ding/worker/collector/interaction_serial_evaluator.py", line 158, in __del__
    self.close()
  File "/home/lab/anaconda3/envs/id2/lib/python3.7/site-packages/ding/worker/collector/interaction_serial_evaluator.py", line 147, in close
    self._env.close()
  File "/home/lab/anaconda3/envs/id2/lib/python3.7/site-packages/ding/envs/env_manager/subprocess_env_manager.py", line 765, in close
    p.send(['close', None, None])
  File "/home/lab/anaconda3/envs/id2/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/lab/anaconda3/envs/id2/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/home/lab/anaconda3/envs/id2/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pip

From the above error, I think the following error is important:
File "/home/lab/anaconda3/envs/id2/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (5x2835 and 2739x128)

this shows some errors about network and env obs. I'm just starting to learn about this framework, so I don't know where to modify.

**Comment by puyuan1996** [comment]
Hi, 
Thank you very much for your question!

The reason for the error is because the dimensions of the input and the linear network do not match.
The linear network requests the shape of input to be 2739, which is the shape of [minigrid obs](https://github.com/opendilab/DI-engine/blob/main/dizoo/minigrid/config/minigrid_r2d2_config.py#L22) in older version of gym-minigrid==1.0.2 in our default config,  but the shape of your real input is 2835, which is the shape of the [latest version](https://github.com/Farama-Foundation/MiniGrid) of minigrid,  so there two ways to fix your issue:
- you can downgrad the version of gym-minigrid to Version: 1.0.2 through:  
`pip install gym-minigrid==1.0.2`
- or you can install the  [latest version](https://github.com/Farama-Foundation/MiniGrid) of minigrid and change the shape of minigrid obs in our  [default config](https://github.com/opendilab/DI-engine/blob/main/dizoo/minigrid/config/minigrid_r2d2_config.py#L22) to 2835.

Good Luck!

**Comment by mao-xu** [comment]
@puyuan1996  thank you. I have run minigrid_r2d2_config.py successfully according to the second advice.

**Comment by mao-xu** [comment]
Hi, @puyuan1996.  I  run minigrid_r2d2_config.py based on installing  gym-minigrid==1.0.2. But, I face the following new error:
"Future gym versions will require that `Env.reset` can be passed `options` to allow the environment initialisation to be passed additional information."
Traceback (most recent call last):
  File "/home/lab/anaconda3/envs/id2/lib/python3.7/site-packages/ding/envs/env_manager/base_env_manager.py", line 111, in __init__
    self._observation_space = self._env_ref.observation_space
  File "/home/lab/anaconda3/envs/id2/lib/python3.7/site-packages/dizoo/minigrid/envs/minigrid_env.py", line 125, in observation_space
    return self._observation_space
AttributeError: 'MiniGridEnv' object has no attribute '_observation_space'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dizoo/minigrid/config/minigrid_r2d2_config.py", line 89, in <module>
    serial_pipeline([main_config, create_config], seed=0)
  File "/home/lab/anaconda3/envs/id2/lib/python3.7/site-packages/ding/entry/serial_entry.py", line 54, in serial_pipeline
    collector_env = create_env_manager(cfg.env.manager, [partial(env_fn, cfg=c) for c in collector_env_cfg])
  File "/home/lab/anaconda3/envs/id2/lib/python3.7/site-packages/ding/envs/env_manager/base_env_manager.py", line 499, in create_env_manager
    return ENV_MANAGER_REGISTRY.build(manager_type, env_fn=env_fn, cfg=manager_cfg)
  File "/home/lab/anaconda3/envs/id2/lib/python3.7/site-packages/ding/utils/registry.py", line 96, in build
    raise e
  File "/home/lab/anaconda3/envs/id2/lib/python3.7/site-packages/ding/utils/registry.py", line 82, in build
    return build_fn(*obj_args, **obj_kwargs)
  File "/home/lab/anaconda3/envs/id2/lib/python3.7/site-packages/ding/envs/env_manager/subprocess_env_manager.py", line 216, in __init__
    super().__init__(env_fn, cfg)
  File "/home/lab/anaconda3/envs/id2/lib/python3.7/site-packages/ding/envs/env_manager/base_env_manager.py", line 120, in __init__
    self._env_ref.reset()
  File "/home/lab/anaconda3/envs/id2/lib/python3.7/site-packages/dizoo/minigrid/envs/minigrid_env.py", line 74, in reset
    obs = self._env.reset()
  File "/home/lab/anaconda3/envs/id2/lib/python3.7/site-packages/gym/core.py", line 491, in reset
    return self.observation(self.env.reset(**kwargs))
  File "/home/lab/anaconda3/envs/id2/lib/python3.7/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
  File "/home/lab/anaconda3/envs/id2/lib/python3.7/site-packages/gym/core.py", line 427, in reset
    return self.env.reset(**kwargs)
  File "/home/lab/anaconda3/envs/id2/lib/python3.7/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/home/lab/anaconda3/envs/id2/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 215, in env_reset_passive_checker
    check_obs(obs, env.observation_space, "reset")
  File "/home/lab/anaconda3/envs/id2/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 159, in check_obs
    ), f"{pre} observation keys is not same as the observation space keys, obs keys: {list(obs.keys())}, space keys: {list(observation_space.spaces.keys())}"
AssertionError: The obs returned by the `reset()` method observation keys is not same as the observation space keys, obs keys: ['image', 'direction', 'mission'], space keys: ['image']

This shows the version of gym doesn't match minigrid. I try the version of gym: 0.25.1, and face the same error.  Can you tell me how to modify the error?

**Comment by puyuan1996** [comment]
Hi,

The problem occurs because the lower version of minigrid only supports gym<=0.24.0, and does not support the higher version of gym. To quickly solve this problem, you can pip install gym==0.24.0. 
However, we still recommend installing the[ latest minigrid ](https://github.com/Farama-Foundation/MiniGrid) and using the [latest version](https://github.com/opendilab/DI-engine) of DI-engine. Regarding the mismatch between the obs shape of [ latest minigrid ](https://github.com/Farama-Foundation/MiniGrid) and our [config](https://github.com/opendilab/DI-engine/blob/main/dizoo/minigrid/config/minigrid_r2d2_config.py), we will fix it immediately.

Good Luck!

**Comment by PaParaZz1** [comment]
This problem has been solved in #500
