### ISSUE TITLE
broken pipe error for pong config, different from https://github.com/opendilab/DI-engine/issues/496

### ISSUE THREAD

**Issue by TheOnlylight** [opendilab/DI-engine#554]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [x] system worker bug
    + [x] system utils bug
    + [ ] code design/refactor
    + [ ] documentation request
    + [ ] new feature request
- [x] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [x] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable:
```python
import ding, torch, sys
print(ding.__version__, torch.__version__, sys.version, sys.platform)

v0.4.4 1.12.0+cu116 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 15:55:03) 
[GCC 10.4.0] linux
```

the wrong for python pong_a2c_config.py:

```python
Traceback (most recent call last):
  File "/home/dijinli/Disk/Workspace/game/DI-engine/dizoo/atari/config/serial/pong/pong_a2c_config.py", line 62, in <module>
    serial_pipeline((main_config, create_config), seed=0)
  File "/home/dijinli/Disk/Workspace/game/ding/lib/python3.9/site-packages/ding/entry/serial_entry.py", line 112, in serial_pipeline
    learner.train(train_data, collector.envstep)
  File "/home/dijinli/Disk/Workspace/game/ding/lib/python3.9/site-packages/ding/worker/learner/base_learner.py", line 165, in wrapper
    ret = fn(*args, **kwargs)
  File "/home/dijinli/Disk/Workspace/game/ding/lib/python3.9/site-packages/ding/worker/learner/base_learner.py", line 205, in train
    log_vars = self._policy.forward(data, **policy_kwargs)
  File "/home/dijinli/Disk/Workspace/game/ding/lib/python3.9/site-packages/ding/policy/a2c.py", line 112, in _forward_learn
    for batch in split_data_generator(data, self._cfg.learn.batch_size, shuffle=True):
  File "/home/dijinli/Disk/Workspace/game/ding/lib/python3.9/site-packages/ding/utils/default_helper.py", line 450, in split_data_generator
    batch = split_fn(data, indices, i, i + split_size)
  File "/home/dijinli/Disk/Workspace/game/ding/lib/python3.9/site-packages/ding/utils/default_helper.py", line 419, in split_fn
    return {k1: split_fn(v1, indices, start, end) for k1, v1 in data.items()}
  File "/home/dijinli/Disk/Workspace/game/ding/lib/python3.9/site-packages/ding/utils/default_helper.py", line 419, in <dictcomp>
    return {k1: split_fn(v1, indices, start, end) for k1, v1 in data.items()}
  File "/home/dijinli/Disk/Workspace/game/ding/lib/python3.9/site-packages/ding/utils/default_helper.py", line 417, in split_fn
    return [split_fn(d, indices, start, end) for d in data]
  File "/home/dijinli/Disk/Workspace/game/ding/lib/python3.9/site-packages/ding/utils/default_helper.py", line 417, in <listcomp>
    return [split_fn(d, indices, start, end) for d in data]
  File "/home/dijinli/Disk/Workspace/game/ding/lib/python3.9/site-packages/ding/utils/default_helper.py", line 421, in split_fn
    return data[indices[start:end]]
TypeError: only integer scalar arrays can be converted to a scalar index
Exception ignored in: <function SampleSerialCollector.__del__ at 0x7f2d559c2550>
Traceback (most recent call last):
  File "/home/dijinli/Disk/Workspace/game/ding/lib/python3.9/site-packages/ding/worker/collector/sample_serial_collector.py", line 195, in __del__
    self.close()
  File "/home/dijinli/Disk/Workspace/game/ding/lib/python3.9/site-packages/ding/worker/collector/sample_serial_collector.py", line 185, in close
    self._env.close()
  File "/home/dijinli/Disk/Workspace/game/ding/lib/python3.9/site-packages/ding/envs/env_manager/subprocess_env_manager.py", line 765, in close
    p.send(['close', None, None])
  File "/home/dijinli/Disk/miniforge3/envs/python39/lib/python3.9/multiprocessing/connection.py", line 211, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/dijinli/Disk/miniforge3/envs/python39/lib/python3.9/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/home/dijinli/Disk/miniforge3/envs/python39/lib/python3.9/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <function InteractionSerialEvaluator.__del__ at 0x7f2d559e3790>
Traceback (most recent call last):
  File "/home/dijinli/Disk/Workspace/game/ding/lib/python3.9/site-packages/ding/worker/collector/interaction_serial_evaluator.py", line 158, in __del__
    self.close()
  File "/home/dijinli/Disk/Workspace/game/ding/lib/python3.9/site-packages/ding/worker/collector/interaction_serial_evaluator.py", line 147, in close
    self._env.close()
  File "/home/dijinli/Disk/Workspace/game/ding/lib/python3.9/site-packages/ding/envs/env_manager/subprocess_env_manager.py", line 765, in close
    p.send(['close', None, None])
  File "/home/dijinli/Disk/miniforge3/envs/python39/lib/python3.9/multiprocessing/connection.py", line 211, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/dijinli/Disk/miniforge3/envs/python39/lib/python3.9/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/home/dijinli/Disk/miniforge3/envs/python39/lib/python3.9/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by zjowowen** [comment]
Hi, this bug has been confirmed due to errors in advanced buffer, which we will fix it soon.

Before it being fixed, please use naive buffer instead.
You can activate naive buffer by adding "replay_buffer=dict(type='naive')," in the dict, create_config or pong_a2c_create_config, in file 'pong_a2c_config.py'.

Anyway, thank you so much for reporting the bug!
