### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Wybgit89** [opendilab/DI-engine#557]
Tue, Dec 13 2022 11:13:36 am
8
Tue, Dec 13 2022 11:13:36 am
job-with-tasks-wyblearner-0.di-job-with-tasks.default.svc.cluster.local,job-with-tasks-wybevaluator-0.di-job-with-tasks.default.svc.cluster.local,job-with-tasks-wybcollector-0.di-job-with-tasks.default.svc.cluster.local,job-with-tasks-wybcollector-1.di-job-with-tasks.default.svc.cluster.local
Tue, Dec 13 2022 11:13:38 am
error when parse platform spec configure: list index out of range
Tue, Dec 13 2022 11:13:38 am
/opt/conda/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 10020). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at /opt/conda/conda-bld/pytorch_1607370172916/work/c10/cuda/CUDAFunctions.cpp:100.)
Tue, Dec 13 2022 11:13:38 am
return torch._C._cuda_getDeviceCount() > 0
Tue, Dec 13 2022 11:13:38 am
Traceback (most recent call last):
Tue, Dec 13 2022 11:13:38 am
File "/opt/conda/bin/ditask", line 8, in <module>
Tue, Dec 13 2022 11:13:38 am
sys.exit(cli_ditask())
Tue, Dec 13 2022 11:13:38 am
File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 829, in __call__
Tue, Dec 13 2022 11:13:38 am
return self.main(*args, **kwargs)
Tue, Dec 13 2022 11:13:38 am
File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 782, in main
Tue, Dec 13 2022 11:13:38 am
rv = self.invoke(ctx)
Tue, Dec 13 2022 11:13:38 am
File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
Tue, Dec 13 2022 11:13:38 am
return ctx.invoke(self.callback, **ctx.params)
Tue, Dec 13 2022 11:13:38 am
File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 610, in invoke
Tue, Dec 13 2022 11:13:38 am
return callback(*args, **kwargs)
Tue, Dec 13 2022 11:13:38 am
File "/opt/conda/lib/python3.8/site-packages/ding/entry/cli_ditask.py", line 67, in cli_ditask
Tue, Dec 13 2022 11:13:38 am
return _cli_ditask(*args, **kwargs)
Tue, Dec 13 2022 11:13:38 am
File "/opt/conda/lib/python3.8/site-packages/ding/entry/cli_ditask.py", line 117, in _cli_ditask
Tue, Dec 13 2022 11:13:38 am
parsed_args = _parse_platform_args(platform, platform_spec, all_args)
Tue, Dec 13 2022 11:13:38 am
File "/opt/conda/lib/python3.8/site-packages/ding/entry/cli_ditask.py", line 90, in _parse_platform_args
Tue, Dec 13 2022 11:13:38 am
raise e
Tue, Dec 13 2022 11:13:38 am
File "/opt/conda/lib/python3.8/site-packages/ding/entry/cli_ditask.py", line 87, in _parse_platform_args
Tue, Dec 13 2022 11:13:38 am
parsed_args = PLATFORM_PARSERS[platform](platform_spec, **all_args)
Tue, Dec 13 2022 11:13:38 am
File "/opt/conda/lib/python3.8/site-packages/ding/entry/cli_parsers/k8s_parser.py", line 151, in k8s_parser
Tue, Dec 13 2022 11:13:38 am
return K8SParser(platform_spec, **kwargs).parse()
Tue, Dec 13 2022 11:13:38 am
File "/opt/conda/lib/python3.8/site-packages/ding/entry/cli_parsers/k8s_parser.py", line 27, in parse
Tue, Dec 13 2022 11:13:38 am
nodename = self.nodelist[procid]
Tue, Dec 13 2022 11:13:38 am
IndexError: list index out of range

8 is the $DI_RANK value I print
job-with-tasks-wyblearner-0.di-job-with-tasks.default.svc.cluster.local,job-with-tasks-wybevaluator-0.di-job-with-tasks.default.svc.cluster.local,job-with-tasks-wybcollector-0.di-job-with-tasks.default.svc.cluster.local,job-with-tasks-wybcollector-1.di-job-with-tasks.default.svc.cluster.local is the $DI_NODES value I print
Could you please tell me the reason of the problem？

following is the yaml I use
apiVersion: diengine.opendilab.org/v2alpha1
kind: DIJob
metadata:
  name: job-with-tasks
spec:
  priority: "normal"  # 表示job的优先级，保留字段，调度中或许可以用到
  backoffLimit: 3  # 表示job允许的最大重启次数，可以为nil，表示无限重启；默认为3，可以通过status.restarts看到实际重启次数
  cleanPodPolicy: "Running"  # 表示job运行完成之后，如何处理worker pods。Running表示job完成后删除所有还在Running的pods
  preemptible: false  # 表示job是否允许被抢占，调度中对job资源改动之后涉及到抢占操作。目前只能设置为false
  volumes:
  - name: cache-volume
    emptyDir:
      medium: Memory
      sizeLimit: 128Mi
  tasks:
  - replicas: 1
    name: "wyblearner"
    type: learner
    template:
      spec:
        containers:
        - name: di-container
          image: opendilab/ding:nightly
          imagePullPolicy: IfNotPresent
          env:
          - name: NCCL_DEBUG
            value: "INFO"
          command: ["/bin/bash", "-c",]
          args:
            - |
              echo $DI_RANK;\
              echo $DI_NODES;\
              ditask --labels learner \
              --package . \
              --main dizoo.atari.example.atari_dqn_dist.main \
              --parallel-workers 1 \
              --topology mesh \
              --platform k8s 
          volumeMounts:
          - name: cache-volume
            mountPath: /dev/shm
        restartPolicy: Never
  - replicas: 1
    name: "wybevaluator"
    type: evaluator
    template:
      spec:
        containers:
        - name: di-container
          image: opendilab/ding:nightly
          imagePullPolicy: IfNotPresent
          env:
          - name: NCCL_DEBUG
            value: "INFO"
          command: ["/bin/bash", "-c",]
          args:
          - |
            echo $DI_RANK;\
            echo $DI_NODES;\
            ditask --labels evaluator \
            --package . \
            --main dizoo.atari.example.atari_dqn_dist.main \
            --parallel-workers 1 \
            --topology mesh \
            --platform k8s 
          volumeMounts:
          - name: cache-volume
            mountPath: /dev/shm
        restartPolicy: Never
  - replicas: 2
    name: "wybcollector"
    type: collector
    template:
      spec:
        volumes:
        - name: test-volume
          hostPath:
            # directory location on host  绑定的节点的文件路径
            path: /root/wyb/
            # this field is optional  此路径类型为必须存在
            type: DirectoryOrCreate
        containers:
        - name: di-container
          image: opendilab/ding:nightly
          imagePullPolicy: IfNotPresent
          env:
          - name: NCCL_DEBUG
            value: "INFO"
          command: ["/bin/bash", "-c",]
          args:
          - |
            echo $DI_RANK;\
            echo $DI_NODES;\
            ditask --labels collector \
            --package . \
            --main dizoo.atari.example.atari_dqn_dist.main \
            --parallel-workers 1 \
            --topology mesh \
            --platform k8s 
          volumeMounts:
          - name: cache-volume
            mountPath: /dev/shm
          # - name: test-volume
          #   mountPath: /ding/wyb/
        restartPolicy: Never

**Comment by sailxjx** [comment]
Could you reformat your logs and code? There seems to be something wrong with environment variables.

**Comment by Wybgit89** [comment]
Thank you for your prompt. It seems that backoffLimit is set to 3 which is wrong. It leads to that my pod restart several times. Each time the pod starts the env variable DI_RANK increase. This leads to the rank is larger than the node number.

**Comment by sailxjx** [comment]
So please check what is causing your process to crash. If the resource utilization is not particularly large (more than the capacity of one node), try to use one pod and multiple workers to run the entire training task.
