### ISSUE TITLE
mario_dqn_example cann't run

### ISSUE THREAD

**Issue by youhu868** [opendilab/DI-engine#582]
在简单修改两处小bug之后，再次运行这个mario_dqn_example脚本时发生了以下报错信息：
Traceback (most recent call last):
  File "/home/xxx/PycharmProjects/DI-engine/dizoo/mario/mario_dqn_example.py", line 65, in <module>
    main()
  File "/home/xxx/PycharmProjects/DI-engine/dizoo/mario/mario_dqn_example.py", line 61, in main
    task.run()
  File "/home/xxx/PycharmProjects/DI-engine/ding/framework/task.py", line 206, in run
    self.forward(fn)
  File "/home/xxx/PycharmProjects/DI-engine/ding/framework/task.py", line 51, in runtime_handler
    return func(task, *args, **kwargs)
  File "/home/xxx/PycharmProjects/DI-engine/ding/framework/task.py", line 274, in forward
    g = fn(ctx)
  File "/home/xxx/PycharmProjects/DI-engine/ding/framework/task.py", line 238, in forward
    g = self.forward(fn, ctx, async_mode=False)
  File "/home/xxx/PycharmProjects/DI-engine/ding/framework/task.py", line 51, in runtime_handler
    return func(task, *args, **kwargs)
  File "/home/xxx/PycharmProjects/DI-engine/ding/framework/task.py", line 274, in forward
    g = fn(ctx)
  File "/home/xxx/PycharmProjects/DI-engine/ding/framework/middleware/functional/evaluator.py", line 253, in _evaluate
    obs = ttorch.as_tensor(env.ready_obs).to(dtype=ttorch.float32)
  File "/home/xxx/anaconda3/envs/py310/lib/python3.10/site-packages/treetensor/utils/func.py", line 25, in _new_func
    return func(
  File "/home/xxx/anaconda3/envs/py310/lib/python3.10/site-packages/treetensor/utils/func.py", line 26, in <genexpr>
    *(mapper(i, x) for i, x in enumerate(args)),
  File "/home/xxx/anaconda3/envs/py310/lib/python3.10/site-packages/treetensor/torch/funcs/construct.py", line 19, in <lambda>
    args_treelize = args_mapping(lambda i, x: TreeValue(x) if isinstance(x, (dict, TreeStorage, TreeValue)) else x)
  File "treevalue/tree/tree/tree.pyx", line 97, in treevalue.tree.tree.tree.TreeValue.__init__
  File "treevalue/tree/tree/tree.pyx", line 38, in treevalue.tree.tree.tree._dict_unpack
TypeError: Expected unicode, got int

=================================================================================================
两处小bug修正如下：

 from ditk import logging
 from ding.model import DQN
 from ding.policy import DQNPolicy
-from ding.envs import DingEnvWrapper, SubprocessEnvManagerV2
+from ding.envs import DingEnvWrapper, SyncSubprocessEnvManager
 from ding.envs.env_wrappers import MaxAndSkipWrapper, WarpFrameWrapper, ScaledFloatFrameWrapper, FrameStackWrapper, \
     EvalEpisodeReturnEnv
 from ding.data import DequeBuffer
@@ -38,10 +38,10 @@ def main():
     cfg = compile_config(main_config, create_cfg=create_config, auto=True)
     with task.start(async_mode=False, ctx=OnlineRLContext()):
         collector_env_num, evaluator_env_num = cfg.env.collector_env_num, cfg.env.evaluator_env_num
-        collector_env = SubprocessEnvManagerV2(
+        collector_env = SyncSubprocessEnvManager(
             env_fn=[wrapped_mario_env for _ in range(collector_env_num)], cfg=cfg.env.manager
         )
-        evaluator_env = SubprocessEnvManagerV2(
+        evaluator_env = SyncSubprocessEnvManager(
             env_fn=[wrapped_mario_env for _ in range(evaluator_env_num)], cfg=cfg.env.manager
         )
 
@@ -57,7 +57,7 @@ def main():
         task.use(nstep_reward_enhancer(cfg))
         task.use(data_pusher(cfg, buffer_))
         task.use(OffPolicyLearner(cfg, policy.learn_mode, buffer_))
-        task.use(CkptSaver(cfg, policy, train_freq=1000))
+        task.use(CkptSaver(policy, cfg.exp_name, train_freq=1000))
         task.run()

**Comment by youhu868** [comment]
thanks, I pull the patch code, the demo is ready to work.
