### ISSUE TITLE
The deque buffer has a small bug

### ISSUE THREAD

**Issue by youhu868** [opendilab/DI-engine#586]
it throw a TypeError when i change 
`replay_buffer=dict(replay_buffer_size=20000, ),`
to
`replay_buffer=dict(
      replay_buffer_size=20000,
      priority=True,
      priority_IS_weight=True,
  )`
for adding priority

```shell
Traceback (most recent call last):
  File "/home/xxx/PycharmProjects/DI-engine/dizoo/classic_control/cartpole/config/cartpole_dqn_config.py", line 65, in <module>
    serial_pipeline((main_config, create_config), seed=0)
  File "/home/xxx/PycharmProjects/DI-engine/ding/entry/serial_entry.py", line 78, in serial_pipeline
    replay_buffer = create_buffer(cfg.policy.other.replay_buffer, tb_logger=tb_logger, exp_name=cfg.exp_name)
  File "/home/xxx/PycharmProjects/DI-engine/ding/worker/replay_buffer/base_buffer.py", line 136, in create_buffer
    return BUFFER_REGISTRY.build(cfg.type, cfg, *args, **kwargs)
  File "/home/xxx/PycharmProjects/DI-engine/ding/utils/registry.py", line 96, in build
    raise e
  File "/home/xxx/PycharmProjects/DI-engine/ding/utils/registry.py", line 82, in build
    return build_fn(*obj_args, **obj_kwargs)
  File "/home/xxx/PycharmProjects/DI-engine/ding/data/buffer/deque_buffer_wrapper.py", line 54, in __init__
    PriorityExperienceReplay(
TypeError: PriorityExperienceReplay.__init__() got multiple values for argument 'IS_weight'
```

```python
        # priority middleware
        if self.cfg.priority:
            self.buffer.use(
                PriorityExperienceReplay(
                    self.buffer,
                    self.cfg.replay_buffer_size,
                    IS_weight=self.cfg.priority_IS_weight,
                    priority_power_factor=self.cfg.priority_power_factor,
                    IS_weight_power_factor=self.cfg.IS_weight_power_factor,
                    IS_weight_anneal_train_iter=self.cfg.IS_weight_anneal_train_iter
                )
            )
```
it should delete `self.cfg.replay_buffer_size,` code.

**Comment by PaParaZz1** [comment]
Thanks for your feedback, we have fixed this bug in above mentioned commit.

**Comment by youhu868** [comment]
You're welcome, let's work together to maintain this project
