### ISSUE TITLE
求助！

### ISSUE THREAD

**Issue by sdsafsdfsaf** [opendilab/DI-engine#629]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [x] documentation request
    + [ ] new feature request
- [x] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [x] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
  ding.version = 0.4.6
  torch.version = 1.12.11 + cu113
  ubuntu
  ```
 按照例子写下面代码的时候，执行出错。
  ``` python
  import os
  import gym
  import torch
  from pettingzoo.mpe import simple_spread_v2
  from tensorboardX import SummaryWriter
  from easydict import EasyDict
  
  from ding.config import compile_config
  from ding.worker import BaseLearner, SampleSerialCollector, InteractionSerialEvaluator, AdvancedReplayBuffer
  from ding.envs import BaseEnvManagerV2, DingEnvWrapper
  from ding.policy import PPOPolicy
  from ding.model.template.vac import VAC
  from ding.utils import set_pkg_seed
  from dizoo.petting_zoo.config.ptz_simple_spread_mappo_config import main_config, create_config
  
  def wrapped_simple_spread_env(cfg):
      return DingEnvWrapper(
          gym.make(cfg.env),
          EasyDict(env_wrapper='default'),
      )
  
  def main(cfg, seed=0):
      cfg['exp_name'] = 'simple_spread_mappo_eval'
      cfg = compile_config(
          cfg,
          BaseEnvManagerV2,
          PPOPolicy,
          BaseLearner,
          SampleSerialCollector,
          InteractionSerialEvaluator,
          AdvancedReplayBuffer,
          save_cfg=True
      )
      cfg.policy.load_path = 'pettingzoo/ptz_simple_spread_mappo_seed0/ckpt/ckpt_best.pth.tar'
      evaluator_env_num = cfg.env.evaluator_env_num
      # evaluator_env = BaseEnvManager(env_fn=[wrapped_simple_spread_env(cfg) for _ in range(evaluator_env_num)], cfg=cfg.env.manager)
      evaluator_env = BaseEnvManagerV2(DingEnvWrapper((simple_spread_v2.parallel_env(N = cfg.env.evaluator_env_num, continuous_actions=True), EasyDict(env_wrapper='default'))))
      evaluator_env.enable_save_replay(replay_path='./simple_spread_mappo_eval/video')
      evaluator_env.seed(seed, dynamic_seed=False)
      set_pkg_seed(seed, use_cuda=cfg.policy.cuda)
  
      model = VAC(**cfg.policy.model)
      policy = PPOPolicy(cfg.policy, model=model)
      policy.eval_mode.load_state_dict(torch.load(cfg.policy.load_path, map_location='cuda'))
      print()
  
      tb_logger = SummaryWriter(os.path.join('./{}/log/'.format(cfg.exp_name), 'serial'))
      evaluator = InteractionSerialEvaluator(
          cfg.policy.eval.evaluator, evaluator_env, policy.eval_mode, tb_logger, exp_name=cfg.exp_name
      )
      evaluator.eval()
  
  if __name__ == "__main__":
       main(main_config)
  ```
错误信息：

  ```bash
  /home/manager/.conda/envs/DI_engine/bin/python /home/sgz/DI_engine/pettingzoo/evaluate_simple_spread_mappo.py 
  /home/manager/.conda/envs/DI_engine/lib/python3.8/site-packages/pettingzoo/utils/wrappers/base.py:59: UserWarning: The `action_spaces` dictionary is deprecated. Use the `action_space` function instead.
    warnings.warn("The `action_spaces` dictionary is deprecated. Use the `action_space` function instead.")
  /home/manager/.conda/envs/DI_engine/lib/python3.8/site-packages/pettingzoo/utils/wrappers/base.py:51: UserWarning: The `observation_spaces` dictionary is deprecated. Use the `observation_space` function instead.
    warnings.warn("The `observation_spaces` dictionary is deprecated. Use the `observation_space` function instead.")
  /home/manager/.conda/envs/DI_engine/lib/python3.8/site-packages/gym/core.py:329: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
    deprecation(
  Traceback (most recent call last):
    File "/home/sgz/DI_engine/pettingzoo/evaluate_simple_spread_mappo.py", line 54, in <module>
      main(main_config)
    File "/home/sgz/DI_engine/pettingzoo/evaluate_simple_spread_mappo.py", line 37, in main
      evaluator_env = BaseEnvManagerV2(DingEnvWrapper((simple_spread_v2.parallel_env(N = cfg.env.evaluator_env_num, continuous_actions=True), EasyDict(env_wrapper='default'))))
    File "/home/manager/.conda/envs/DI_engine/lib/python3.8/site-packages/ding/envs/env/ding_env_wrapper.py", line 41, in __init__
      self._observation_space = self._env.observation_space
    File "/home/manager/.conda/envs/DI_engine/lib/python3.8/site-packages/gym/core.py", line 337, in __getattr__
      return getattr(self.env, name)
  AttributeError: 'tuple' object has no attribute 'observation_space'
  
  Process finished with exit code 1
  ```

pettingzoo 中 mpe环境相关运行示例较少，无法参考

**Comment by puyuan1996** [comment]
首先非常感谢你对 DI-engine 的关注。

你这里应该是想加载在 simple_spread_v2 环境上预训练好的 mappo 模型，然后执行评估程序，一个替代的实现可以参考 [PR631](https://github.com/opendilab/DI-engine/pull/631) 里面的`dizoo/petting_zoo/eval/ptz_simple_spread_mappo_eval_config.py`。

关于你上面的报错，原因在于目前 DingEnvWrapper 暂不支持多智能体环境，这个功能我们后续会开发，谢谢你的耐心和关注哈。
