### ISSUE TITLE
运行DI-Zoo里面写好的config报错

### ISSUE THREAD

**Issue by xujinming01** [opendilab/DI-engine#646]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [x] system utils bug
    + [ ] code design/refactor
    + [ ] documentation request
    + [ ] new feature request
- [x] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [x] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
  ```

```shell
v0.4.7 1.12.1+cpu 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)] win32
```

直接在Pycharm里面运行`DI-engine\dizoo\gym_hybrid\config\gym_hybrid_pdqn_config.py`报错：

```python
Traceback (most recent call last):
  File "C:\Users\arche\code\repository\DI-engine\dizoo\gym_hybrid\config\gym_hybrid_pdqn_config.py", line 76, in <module>
    serial_pipeline([main_config, create_config], seed=0, max_env_step=int(1e7))
  File "C:\Users\arche\code\repository\DI-engine\ding\entry\serial_entry.py", line 97, in serial_pipeline
    stop, eval_info = evaluator.eval(learner.save_checkpoint, learner.train_iter, collector.envstep)
  File "C:\Users\arche\code\repository\DI-engine\ding\worker\collector\interaction_serial_evaluator.py", line 314, in eval
    return_info = to_item(return_info)
  File "C:\Users\arche\code\repository\DI-engine\ding\torch_utils\data_helper.py", line 301, in to_item
    return [to_item(d) for d in data]
  File "C:\Users\arche\code\repository\DI-engine\ding\torch_utils\data_helper.py", line 301, in <listcomp>
    return [to_item(d) for d in data]
  File "C:\Users\arche\code\repository\DI-engine\ding\torch_utils\data_helper.py", line 303, in to_item
    return {k: to_item(v) for k, v in data.items()}
  File "C:\Users\arche\code\repository\DI-engine\ding\torch_utils\data_helper.py", line 303, in <dictcomp>
    return {k: to_item(v) for k, v in data.items()}
  File "C:\Users\arche\code\repository\DI-engine\ding\torch_utils\data_helper.py", line 299, in to_item
    return data.item()
ValueError: only one element tensors can be converted to Python scalars
```
调试查看了一下 `return_info` 的信息：

```python
[{'eval_episode_return': tensor([-1.2000]), 'action_args_mask': tensor([[1., 0.],
        [0., 1.],
        [0., 0.]])}, {'eval_episode_return': tensor([-1.2000]), 'action_args_mask': tensor([[1., 0.],
        [0., 1.],
        [0., 0.]])}, {'eval_episode_return': tensor([-1.2000]), 'action_args_mask': tensor([[1., 0.],
        [0., 1.],
        [0., 0.]])}, {'eval_episode_return': tensor([-1.2000]), 'action_args_mask': tensor([[1., 0.],
        [0., 1.],
        [0., 0.]])}, {'eval_episode_return': tensor([-1.2000]), 'action_args_mask': tensor([[1., 0.],
        [0., 1.],
        [0., 0.]])}]
```
是不是 `to_item()` 不支持多维的 tensor

**Comment by PaParaZz1** [comment]
这个问题已经在最新的 main 分支 commit 中修复了，你可以看下你那边运行环境是否还存在该问题。

**Comment by xujinming01** [comment]
Ok, thanks.
