### ISSUE TITLE
failed to run gym_hybrid_pdqn_config.py

### ISSUE THREAD

**Issue by super1603** [opendilab/DI-engine#668]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [x] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [ ] documentation request
    + [ ] new feature request
- [x] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [x] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
  v0.4.7 1.12.1+cu102 3.9.16 (main, Mar  8 2023, 14:00:05) 
  [GCC 11.2.0] linux 
 ```
```
  安装DI-engine
```
git clone https://github.com/opendilab/DI-engine.git
cd DI-engine
pip install .
```
  安装gym_hybrid环境
```
cd gym-hybrid && pip install .
```
  安装cv模块
```
pip install python-opencv
```
  运行python dizoo/gym_hybrid/config/gym_hybrid_pdqn_config.py以及同目录下其他三个.py文件都会报如下错误
```
Traceback (most recent call last):
  File "/home/astlab/hanhongwei/DI-engine/dizoo/gym_hybrid/config/gym_hybrid_pdqn_config.py", line 76, in <module>
    serial_pipeline([main_config, create_config], seed=0, max_env_step=int(1e7))
  File "/home/astlab/anaconda3/envs/hhwdi/lib/python3.9/site-packages/ding/entry/serial_entry.py", line 101, in serial_pipeline
    new_data = collector.collect(train_iter=learner.train_iter, policy_kwargs=collect_kwargs)
  File "/home/astlab/anaconda3/envs/hhwdi/lib/python3.9/site-packages/ding/worker/collector/sample_serial_collector.py", line 320, in collect
    self._output_log(train_iter)
  File "/home/astlab/anaconda3/envs/hhwdi/lib/python3.9/site-packages/ding/worker/collector/sample_serial_collector.py", line 359, in _output_log
    'reward_mean': np.mean(episode_return),
  File "<__array_function__ internals>", line 200, in mean
  File "/home/astlab/anaconda3/envs/hhwdi/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 3464, in mean
    return _methods._mean(a, axis=axis, dtype=dtype,
  File "/home/astlab/anaconda3/envs/hhwdi/lib/python3.9/site-packages/numpy/core/_methods.py", line 165, in _mean
    arr = asanyarray(a)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (69,) + inhomogeneous part.
Exception ignored in: <function SampleSerialCollector.__del__ at 0x7f548cb83a60>
Traceback (most recent call last):
  File "/home/astlab/anaconda3/envs/hhwdi/lib/python3.9/site-packages/ding/worker/collector/sample_serial_collector.py", line 196, in __del__
    self.close()
  File "/home/astlab/anaconda3/envs/hhwdi/lib/python3.9/site-packages/ding/worker/collector/sample_serial_collector.py", line 186, in close
    self._env.close()
  File "/home/astlab/anaconda3/envs/hhwdi/lib/python3.9/site-packages/ding/envs/env_manager/subprocess_env_manager.py", line 635, in close
    p.send(['close', None, None])
  File "/home/astlab/anaconda3/envs/hhwdi/lib/python3.9/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/astlab/anaconda3/envs/hhwdi/lib/python3.9/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/home/astlab/anaconda3/envs/hhwdi/lib/python3.9/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <function InteractionSerialEvaluator.__del__ at 0x7f548cb9fca0>
Traceback (most recent call last):
  File "/home/astlab/anaconda3/envs/hhwdi/lib/python3.9/site-packages/ding/worker/collector/interaction_serial_evaluator.py", line 158, in __del__
    self.close()
  File "/home/astlab/anaconda3/envs/hhwdi/lib/python3.9/site-packages/ding/worker/collector/interaction_serial_evaluator.py", line 147, in close
    self._env.close()
  File "/home/astlab/anaconda3/envs/hhwdi/lib/python3.9/site-packages/ding/envs/env_manager/subprocess_env_manager.py", line 635, in close
    p.send(['close', None, None])
  File "/home/astlab/anaconda3/envs/hhwdi/lib/python3.9/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/astlab/anaconda3/envs/hhwdi/lib/python3.9/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/home/astlab/anaconda3/envs/hhwdi/lib/python3.9/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

其他三个算法运行一段时间后也会报同样的错误，请问这个是什么问题呢？

**Comment by PaParaZz1** [comment]
谢谢你的反馈，这个错误和 issue #664 中描述的应该是一个问题，我们会在本周内解决这个问题，你可以关注那个 issue 的相关进展，这个 issue 我就先关闭了

**Comment by super1603** [comment]
好的，感谢您
