### ISSUE TITLE
How to run the example of Decision Transformer

### ISSUE THREAD

**Issue by shimoshida** [opendilab/DI-engine#670]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [x] documentation request
    + [ ] new feature request
- [x] I have visited the [readme](https://github.com/opendilab/DI-engine/blob/github-dev/README.md) and [doc](https://opendilab.github.io/DI-engine/)
- [x] I have searched through the [issue tracker](https://github.com/opendilab/DI-engine/issues) and [pr tracker](https://github.com/opendilab/DI-engine/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable:

  ```python
  import ding, torch, sys
  print(ding.__version__, torch.__version__, sys.version, sys.platform)
  # v0.4.7 1.12.1 3.10.9 (main, Dec 18 2022, 10:32:28) [Clang 14.0.0 (clang-1400.0.29.202)] darwin
  ```

## Question
I try to run the example of decision transformer 
- https://github.com/opendilab/DI-engine/blob/main/dizoo/d4rl/entry/d4rl_dt_main.py

I have modified the dataset path and run, but the following error was obtained. How to fix this?
```
DI-engine/dizoo/d4rl/config/hopper medium_expert
Traceback (most recent call last):
  File "/Users/moshida/.pyenv/versions/3.10.9/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/moshida/.pyenv/versions/3.10.9/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/moshida/Desktop/dt/src/samples/d4rl-dt-main.py", line 61, in <module>
    train(args)
  File "/Users/moshida/Desktop/dt/src/samples/d4rl-dt-main.py", line 46, in train
    serial_pipeline_dt(config, seed=args.seed, max_train_iter=3000)
  File "/Users/moshida/Desktop/dt/.venv/lib/python3.10/site-packages/ding/entry/serial_entry_decision_transformer.py", line 65, in serial_pipeline_dt
    policy = create_policy(cfg.policy, model=model, enable_field=['learn', 'eval'])
  File "/Users/moshida/Desktop/dt/.venv/lib/python3.10/site-packages/ding/policy/base_policy.py", line 344, in create_policy
    return POLICY_REGISTRY.build(cfg.type, cfg=cfg, **kwargs)
  File "/Users/moshida/Desktop/dt/.venv/lib/python3.10/site-packages/ding/utils/registry.py", line 96, in build
    raise e
  File "/Users/moshida/Desktop/dt/.venv/lib/python3.10/site-packages/ding/utils/registry.py", line 82, in build
    return build_fn(*obj_args, **obj_kwargs)
  File "/Users/moshida/Desktop/dt/.venv/lib/python3.10/site-packages/ding/policy/base_policy.py", line 90, in __init__
    model = self._create_model(cfg, model)
  File "/Users/moshida/Desktop/dt/.venv/lib/python3.10/site-packages/ding/policy/base_policy.py", line 144, in _create_model
    return create_model(model_cfg)
  File "/Users/moshida/Desktop/dt/.venv/lib/python3.10/site-packages/ding/model/common/utils.py", line 18, in create_model
    return MODEL_REGISTRY.build(cfg.pop("type"), **cfg)
  File "/Users/moshida/Desktop/dt/.venv/lib/python3.10/site-packages/ding/utils/registry.py", line 96, in build
    raise e
  File "/Users/moshida/Desktop/dt/.venv/lib/python3.10/site-packages/ding/utils/registry.py", line 82, in build
    return build_fn(*obj_args, **obj_kwargs)
TypeError: DecisionTransformer.__init__() got an unexpected keyword argument 'encoder_hidden_size_list'
```

**Comment by puyuan1996** [comment]
Hello,

The error you encountered is related to the DecisionTransformer's initialization method receiving an incorrect parameter called `encoder_hidden_size_list`. 

In `d4rl_dt_main.py`, the default config should be `hopper_medium_expert_dt_config.py`. Please check whether the model field in this file contains the parameter `encoder_hidden_size_list`. If it does, simply remove it, as the DecisionTransformer model does not require this parameter.

Best wishes.
