### ISSUE TITLE
Error occurs when async_mode=True in example/ppo.py

### ISSUE THREAD

**Issue by weixians** [opendilab/DI-engine#707]
我尝试运行ding/example/ppo.py文件，当async_mode=False的时候，可以正常跑，但是将其改为True的时候，就会报错，无法运行，具体如下：

`Traceback (most recent call last):
  File "D:\BaiduSyncdisk\xxx\workspace\RL\test\DI-engine\ding\example\ppo.py", line 45, in <module>
    main()
  File "D:\BaiduSyncdisk\xxx\workspace\RL\test\DI-engine\ding\example\ppo.py", line 41, in main
    task.run()
  File "D:\BaiduSyncdisk\xxx\workspace\RL\test\DI-engine\ding\framework\task.py", line 209, in run
    self.sync()
  File "D:\BaiduSyncdisk\xxx\workspace\RL\test\DI-engine\ding\framework\task.py", line 398, in sync
    self._async_loop.run_until_complete(self.sync_tasks())
  File "C:\Users\ASUS2020\.conda\envs\diengine\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "D:\BaiduSyncdisk\xxx\workspace\RL\test\DI-engine\ding\framework\task.py", line 410, in sync_tasks
    raise e
  File "C:\Users\ASUS2020\.conda\envs\diengine\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\BaiduSyncdisk\xxx\workspace\RL\test\DI-engine\ding\framework\task.py", line 274, in forward
    g = fn(ctx)
  File "D:\BaiduSyncdisk\xxx\workspace\RL\test\DI-engine\ding\framework\task.py", line 238, in forward
    g = self.forward(fn, ctx, async_mode=False)
  File "D:\BaiduSyncdisk\xxx\workspace\RL\test\DI-engine\ding\framework\task.py", line 51, in runtime_handler
    return func(task, *args, **kwargs)
  File "D:\BaiduSyncdisk\xxx\workspace\RL\test\DI-engine\ding\framework\task.py", line 274, in forward
    g = fn(ctx)
  File "D:\BaiduSyncdisk\xxx\workspace\RL\test\DI-engine\ding\framework\middleware\functional\advantage_estimator.py", line 45, in _gae
    data = ttorch_collate(data)  # ttorch.Tensor
  File "D:\BaiduSyncdisk\xxx\workspace\RL\test\DI-engine\ding\utils\data\collate_fn.py", line 30, in ttorch_collate
    x = ttorch.stack(x)
  File "C:\Users\ASUS2020\.conda\envs\diengine\lib\site-packages\treevalue\tree\func\func.py", line 56, in _new_func
    return _treelized(*args, **kwargs)
  File "treevalue\tree\func\cfunc.pyx", line 181, in treevalue.tree.func.cfunc._w_func_treelize_run
  File "treevalue\tree\func\cfunc.pyx", line 76, in treevalue.tree.func.cfunc._c_func_treelize_run
  File "C:\Users\ASUS2020\.conda\envs\diengine\lib\site-packages\treetensor\torch\funcs\operation.py", line 356, in stack
    return stream_call(torch.stack, tensors, *args, **kwargs)
  File "C:\Users\ASUS2020\.conda\envs\diengine\lib\site-packages\treetensor\torch\stream.py", line 40, in stream_call
    return func(*args, **kwargs)
TypeError: stack(): argument 'tensors' (position 1) must be tuple of Tensors, not NoneType
`

**Comment by PaParaZz1** [comment]
这个参数为 True 的时候还存在一些适配性问题，建议暂时先不要打开。

**Comment by weixians** [comment]
> 这个参数为 True 的时候还存在一些适配性问题，建议暂时先不要打开。

好的，如果可以了麻烦说下，非常感谢。我觉得这个Idea是非常棒的
