### ISSUE TITLE
KeyError: 'obs_shape'

### ISSUE THREAD

**Issue by WangJuan6** [opendilab/DI-engine#812]
Dear Author,
I run the code by python ding/example/mappo.py, but I got an error:
```
Traceback (most recent call last):
  File "/data/projects/20240701/DI-engine/ding/example/mappo.py", line 45, in <module>
    main()
  File "/data/projects/20240701/DI-engine/ding/example/mappo.py", line 36, in main
    task.use(gae_estimator(cfg, policy.collect_mode))
  File "/home/wj/anaconda3/envs/di/lib/python3.9/site-packages/ding/framework/middleware/functional/advantage_estimator.py", line 35, in gae_estimator
    obs_shape = cfg['policy']['model']['obs_shape']
KeyError: 'obs_shape'
```
Can you help me to solve this problem?
Thanks

**Comment by PaParaZz1** [comment]
Thanks for your feedback! We have fixed this problem in the latest commit.

**Comment by WangJuan6** [comment]
It works, thank you!
